name: Cleanup bad PR

on:
  pull_request_target:
    types: [opened, reopened]

permissions:
  contents: read

jobs:
  close-pr:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 1
          persist-credentials: false
          sparse-checkout: |
            _config.yml
      - id: config
        shell: ruby {0}
        run: |
          require "yaml"

          config = YAML.safe_load(File.read("_config.yml"), aliases: true) || {}
          customized = !config.fetch("url", nil).nil?
          File.open(ENV.fetch("GITHUB_OUTPUT"), "a") do |file|
            file.puts("customized=#{customized}")
          end
      - uses: actions-ecosystem/action-add-labels@v1
        if: steps.config.outputs.customized == 'false'
        with:
          labels: |
            Type: Invalid
            Type: Spam
      - uses: superbrothers/close-pull-request@v3
        if: steps.config.outputs.customized == 'false'
        with:
          # Optional. Post an issue comment just before closing a pull request.
          comment: |
            **You have created a Pull Request to the wrong repository.** This is the repository for [Minimal Mistakes][1], the free Jekyll theme. See [GitHub Docs: About pull requests][2] if you need help.

              [1]: https://mmistakes.github.io/minimal-mistakes/
              [2]: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests
      - uses: sudo-bot/action-pull-request-lock@v2
        if: steps.config.outputs.customized == 'false'
        with:
          github-token: ${{ github.token }}
          number: ${{ github.event.pull_request.number }}
          lock-reason: spam
